### ISSUE TITLE
Failed to download action 

### ISSUE THREAD

**Issue by muhammet** [AdWerx/pronto-ruby#1]
![image](https://user-images.githubusercontent.com/989759/66258579-8947fc00-e7af-11e9-8b45-644740f40051.png)

**Comment by jbielick** [comment]
Hello! Thanks for posting this issue. For now, I've delisted this Action as it isn't ready for public use. Thanks for understanding.

**Comment by jbielick** [comment]
`v1.0.0-rc3` should be ready for previewing / use.
