### ISSUE TITLE
Dependabot - `403 - Resource not accessible by integration`

### ISSUE THREAD

**Issue by mbajur** [AdWerx/pronto-ruby#197]
Hey!

I am trying to use this action and it all works great when i am the one who opens/pushes the changes. However, once dependabot is opening a PR, this action is always failing with:

```
Faraday::Error::ClientError.inherited called from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
/runner/src/github_action_check_run_formatter.rb:[10](https://github.com/xxx/yyy/actions/runs/6343338290/job/17230992679?pr=506#step:8:11): warning: already initialized constant Pronto::Formatter::FORMATTERS
/usr/local/bundle/gems/pronto-0.10.0/lib/pronto/formatter/formatter.rb:13: warning: previous definition of FORMATTERS was here
/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/xxx/yyy/check-runs: 403 - Resource not accessible by integration // See: https://docs.github.com/rest/checks/runs#create-a-check-run (Octokit::Forbidden)
```

I tried every single solution i've found on the internet to try to fix it but nothing worked. Including https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/resource-not-accessible-by-integration

**Comment by jbielick** [comment]
What are you expecting to happen when dependabot opens a PR? Are you trying to ignore dependabot pull requests? Or run this action for them?

**Comment by mbajur** [comment]
Well, i could easily disable/ignore that but there are two checks defined that has to pass for every PR therefore no PR opened by dependabot will ever become green because of these two checks.

Basically - i see no point of running pronto for rubocop but required checks defined on repo level will not allow me to ignore the pronto action. But please correct me if I'm wrong :)

**Comment by jbielick** [comment]
I'm not sure what I could do in the action code to prevent the action from running or ensure that it passes. The github token provided for the workflow does not have the proper permissions to create the check run on the commit. If there's no token that can create a passing check run on the commit, the required checks on the PR can't be green. 

I think the only way around this is something on your side. Either re-pushing the dependabot commits with a different committer (in which a more privileged token would be issued for the workflow run) or an automated way of re-syncing the PR in which _you_ or another trusted user are the actor.

**Comment by mbajur** [comment]
That's exactly what i was afraid to hear ;) But wait, isn't that possible to tell pronto used by this action to use a different token i could issue myself with proper permissions instead of using the default one?

**Comment by jbielick** [comment]
If you were to write a conditional in your workflow to detect if the workflow run was triggered by an untrusted user (dependabot) and pass a PAT or something in lieu of an authorized github workflow token I don't see why that wouldn't work, but it might be considered a security vulnerability. The github token is passed as an ENV variable to this action, so you could pass in whatever value you want.

**Comment by jbielick** [comment]
I might suggest something like adding a trigger to your pronto workflow that runs when a particular label is added. That way you can label a dependabot PR with something like "ok-to-pronto" and when _you_ add that label, a trusted user github token would be used in the workflow and allow it to run. It may affect how you determine the right SHA to checkout and run pronto against, but there are also other alternatives like closing and reopening the PR (depends on a pull_request trigger).

**Comment by mbajur** [comment]
Thank you for all the information. I managed to fix it by adding 

```
    permissions:
      checks: write
      contents: read
 ```
 
 to `run:` block
