### ISSUE TITLE
Base dockerfile location

### ISSUE THREAD

**Issue by tboby** [AdWerx/pronto-ruby#3]
Hi, 

What's happened to https://github.com/AdWerx/dockerfiles/tree/master/pronto-ruby ?

I'm trying to support running my action on gitlab and it looks like moving from Checks API to pronto is a good way to do that. Your work looks like it'd be really useful to maintain the Checks API support, but I suspect some of the important bits are inside that base image!

**Comment by jbielick** [comment]
Hi @tboby 

I'm not sure I understand your question, but I can help clarify what's in each docker image.

`adwerx/dockerfiles` contains / builds `adwerx/pronto-ruby` ruby image via [its Dockerfile](https://github.com/AdWerx/dockerfiles/blob/master/pronto-ruby/Dockerfile). This image is available as `adwerx/pronto-ruby` [in docker hub](https://hub.docker.com/r/adwerx/pronto-ruby). This image contains ruby, pronto, and pronto runners. That's all. 

This repo is specifically made for [the GitHub Action](https://github.com/marketplace/actions/pronto-ruby). The [Dockerfile](https://github.com/AdWerx/pronto-ruby/blob/master/Dockerfile) in _this_ repo is based off of the `adwerx/pronto-ruby` image. This repo contains extra code required to run our `adwerx/pronto-ruby` image as a GitHub action [with Checks API output](https://github.com/AdWerx/pronto-ruby/blob/master/src/github_action_check_run_formatter.rb). There is no docker image in docker hub for the image built by this repo—it is built in GitHub Actions when the action runs.

I'm not familiar with how GitLab Actions work. All of the code here is open source. What part in particular are you looking for?

**Comment by tboby** [comment]
@jbielick The repo is private :)

**Comment by jbielick** [comment]
Ah 🤦‍♂! I totally overlooked that :)

I just moved the base dockerfile into this repo as `Dockerfile`. The GitHub Action dockerfile is `Dockerfile.action`. Is that the Dockerfile you're looking for?

**Comment by tboby** [comment]
That's the one, thanks :)
