### ISSUE TITLE
pronto-ruby -v 2.3.1 not reporting back

### ISSUE THREAD

**Issue by sebastian-palma** [AdWerx/pronto-ruby#9]
I've just added this Github Action to a Rails project and I saw that the reports aren't being "published" after running. I can see in the logs that there were issues, but nothing is available then in the "checks" tab.

Is there any configuration I'm missing?

I tried with and without specific runners, same problem.

**Comment by jbielick** [comment]
Could you share the logs and your action/workflow yaml (sensitive values removed)?

**Comment by jbielick** [comment]
Do you have a pronto config? A config like so may be necessary:

```yaml
github:
  slug: myorg/myrepo
```

**Comment by jbielick** [comment]
@sebastian-palma did you see my question above?

**Comment by sebastian-palma** [comment]
Yes @jbielick. It looks like:

```yaml
rubocop:
  severities:
    refactor: info
    warning: error
  suggestions: true
```
